export enum VoiceStateEnum {
  SELF_MUTED = "SELF_MUTED",
  SELF_DEAFENED = "SELF_DEAFENED",
  SERVER_MUTED = "SERVER_MUTED",
  SERVER_DEAFENED = "SERVER_DEAFENED",
  STREAMING = "STREAMING",
  FILMING = "FILMING",
}
